#!/bin/bash

set -e

DATABASE_URL=postgresql://postgres:test@localhost:5432/users
DATABASE_USER=postgres
DATABASE_PASSWORD=test
DATABASE_HOST=localhost


DATABASE_HOST=$DATABASE_HOST DATABASE_USER=$DATABASE_USER \
 DATABASE_PASSWORD=$DATABASE_PASSWORD APP_JWT_SECRET=test \
 ADMIN_JWT_SECRET=test DATABASE_URL=$DATABASE_URL \
 AWS_SECRET_ACCESS_KEY=test AWS_ACCESS_KEY_ID=test \
 AWS_DEFAULT_REGION=test pytest "$@"
